version: '3'

services:
  cms:
    container_name: cms
    image: cms
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - '8181:80'
    networks:
      - server-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms.rule=Host(`cms.chrisgrime.com`)"
      - "traefik.http.routers.cms.entrypoints=websecure"
      - "traefik.http.routers.cms.tls.certresolver=myresolver"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8182:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - server-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma.chrisgrime.com`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls.certresolver=myresolver"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: cms
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - server-network

networks:
  server-network:
    external: true