version: '3'

services:
  web:
    image: php74:latest
    ports:
      - '80:80'
    volumes:
      - /Users/vincentb/Sites/_docker/apache:/etc/apache2/sites-enabled
      - /Users/vincentb/Sites:/var/www/html
      - /Users/vincentb/Sites/_docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
    extra_hosts:
      - 'ax710.test:127.0.0.1'
      # - 'some-other-host.test:127.0.0.1'
    networks:
      - dev-env
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - /Users/vincentb/Sites/_docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - dev-env
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'vincentb'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'vincentb'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dev-env
volumes:
  mysqldata: {}
networks:
  dev-env: {}